### ISSUE TITLE
Unhandled exception has occured in your application.

### ISSUE THREAD

**Issue by root-reindeer-flotilla** [VE3NEA/HeatMapView#1]
Here's an error I got when trying to use this plugin.

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at SDRSharp.HeatMapView.HeatMapPanel.DrawScale(Graphics g)
   at SDRSharp.HeatMapView.HeatMapPanel.HitMapViewFrontControl_Paint(Object sender, PaintEventArgs e)
   at System.Windows.Forms.Control.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
SDRSharp
    Assembly Version: 1.0.0.1666
    Win32 Version: 1.0.0.1666
    CodeBase: file:///C:/Users/patq9_000/Downloads/Permanent%20Downloads/sdr-install/newq/sdrsharp-x86/SDRSharp.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
SDRSharp.Radio
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/patq9_000/Downloads/Permanent%20Downloads/sdr-install/newq/sdrsharp-x86/SDRSharp.Radio.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
SDRSharp.Common
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/patq9_000/Downloads/Permanent%20Downloads/sdr-install/newq/sdrsharp-x86/SDRSharp.Common.DLL
----------------------------------------
SDRSharp.PanView
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/patq9_000/Downloads/Permanent%20Downloads/sdr-install/newq/sdrsharp-x86/SDRSharp.PanView.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
SDRSharp.CollapsiblePanel
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/patq9_000/Downloads/Permanent%20Downloads/sdr-install/newq/sdrsharp-x86/SDRSharp.CollapsiblePanel.DLL
----------------------------------------
SDRSharp.FrequencyEdit
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/patq9_000/Downloads/Permanent%20Downloads/sdr-install/newq/sdrsharp-x86/SDRSharp.FrequencyEdit.DLL
----------------------------------------
SDRSharp.HackRF
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/patq9_000/Downloads/Permanent%20Downloads/sdr-install/newq/sdrsharp-x86/SDRSharp.HackRF.DLL
----------------------------------------
SDRSharp.RTLSDR
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/patq9_000/Downloads/Permanent%20Downloads/sdr-install/newq/sdrsharp-x86/SDRSharp.RTLSDR.DLL
----------------------------------------
SDRSharp.RTLTCP
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/patq9_000/Downloads/Permanent%20Downloads/sdr-install/newq/sdrsharp-x86/SDRSharp.RTLTCP.DLL
----------------------------------------
SDRSharp.FUNcube
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/patq9_000/Downloads/Permanent%20Downloads/sdr-install/newq/sdrsharp-x86/SDRSharp.FUNcube.DLL
----------------------------------------
SDRSharp.FUNcubeProPlus
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/patq9_000/Downloads/Permanent%20Downloads/sdr-install/newq/sdrsharp-x86/SDRSharp.FUNcubeProPlus.DLL
----------------------------------------
SDRSharp.SoftRock
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/patq9_000/Downloads/Permanent%20Downloads/sdr-install/newq/sdrsharp-x86/SDRSharp.SoftRock.DLL
----------------------------------------
SDRSharp.SDRIQ
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/patq9_000/Downloads/Permanent%20Downloads/sdr-install/newq/sdrsharp-x86/SDRSharp.SDRIQ.DLL
----------------------------------------
SDRSharp.SDRIP
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/patq9_000/Downloads/Permanent%20Downloads/sdr-install/newq/sdrsharp-x86/SDRSharp.SDRIP.DLL
----------------------------------------
SDRSharp.AfedriSDRNet
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/patq9_000/Downloads/Permanent%20Downloads/sdr-install/newq/sdrsharp-x86/SDRSharp.AfedriSDRNet.DLL
----------------------------------------
SDRSharp.DNR
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/patq9_000/Downloads/Permanent%20Downloads/sdr-install/newq/sdrsharp-x86/SDRSharp.DNR.DLL
----------------------------------------
SDRSharp.NoiseBlanker
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/patq9_000/Downloads/Permanent%20Downloads/sdr-install/newq/sdrsharp-x86/SDRSharp.NoiseBlanker.DLL
----------------------------------------
SDRSharp.WavRecorder
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/patq9_000/Downloads/Permanent%20Downloads/sdr-install/newq/sdrsharp-x86/SDRSharp.WavRecorder.DLL
----------------------------------------
SDRSharp.ZoomFFT
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/patq9_000/Downloads/Permanent%20Downloads/sdr-install/newq/sdrsharp-x86/SDRSharp.ZoomFFT.DLL
----------------------------------------
SDRSharp.BandPlan
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/patq9_000/Downloads/Permanent%20Downloads/sdr-install/newq/sdrsharp-x86/SDRSharp.BandPlan.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
SDRSharp.FrequencyManager
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/patq9_000/Downloads/Permanent%20Downloads/sdr-install/newq/sdrsharp-x86/SDRSharp.FrequencyManager.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
SDRSharp.Diagnostics
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/patq9_000/Downloads/Permanent%20Downloads/sdr-install/newq/sdrsharp-x86/SDRSharp.Diagnostics.DLL
----------------------------------------
SDRSharp.AudioWaterfall
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/patq9_000/Downloads/Permanent%20Downloads/sdr-install/newq/sdrsharp-x86/SDRSharp.AudioWaterfall.DLL
----------------------------------------
SDRSharp.HeatMapView
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/patq9_000/Downloads/Permanent%20Downloads/sdr-install/newq/sdrsharp-x86/SDRSharp.HeatMapView.DLL
----------------------------------------
System.Web.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Web.Extensions/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.Extensions.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.



```

**Comment by patq911** [comment]
Also when clicking continue and ignoring the error and trying to load a csv it says 

> Unable to generate heat map. Error: Invalid JSON primitive: access.

**Comment by VE3NEA** [comment]
Fixed.

**Comment by patq911** [comment]
Sorry but it's still not working.

`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at SDRSharp.HeatMapView.HeatMapPanel.DrawTriangle(Graphics g)
   at SDRSharp.HeatMapView.HeatMapPanel.HitMapViewFrontControl_Paint(Object sender, PaintEventArgs e)
   at System.Windows.Forms.Control.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

SDR# version is 1666 and I'm using windows 10, sorry I forgot to mention that before.

**Comment by VE3NEA** [comment]
Here is a better fix. The problem was occurring only when the heatmap was not loaded, but the plugin was enabled. The UI is not supposed to allow this, I am wondering how you managed to enable the plugin that had no heatmaps in the list, or no heatmap was selected. 

The fix ensures that the plugin panel is repainted properly even in this situation, but I would like to prevent such situation from occurring in the first place.

**Comment by root-reindeer-flotilla** [comment]
I have a few heatmaps that I've done, but the problem is I don't actually know how good they are until I visually see them.

It works! I did a wideband for an hour last night and that one seemed to have worked.
